### ISSUE TITLE
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

### ISSUE THREAD

**Issue by jralduaveuthey** [anna-geller/dataflow-ops#4]
When running the workflow "1 Initial - ECS Prefect agent" (.github\workflows\ecs_prefect_agent.yml) I get the error below:

Other Info:
- The error appears in the job "Prefect Blocks & S3 Upload" in the step "Upload to S3 - maintenance flow"
- The block "S3 /prod" is created in the Prefect Cloud
- The AWS Account has admin rights

Why AccessDenied? 

```
Run prefect deployment build utilities/maintenance.py:maintenance -n $PROJECT -sb s3/$BLOCK -q $PROJECT -v $GITHUB_SHA -a -t maintenance --interval 10
Found flow 'maintenance'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/s3fs/core.py", line 112, in _error_wrapper
An exception occurred.
    return await func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line [20](https://github.com/jralduaveuthey/dataflow-ops/actions/runs/3541983497/jobs/5946948982#step:9:21)1, in coroutine_wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 152, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line [28](https://github.com/jralduaveuthey/dataflow-ops/actions/runs/3541983497/jobs/5946948982#step:9:29)7, in wrapper
    return await func(*args)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/prefect/cli/deployment.py", line 876, in build
    deployment = await Deployment.build_from_flow(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/prefect/deployments.py", line 728, in build_from_flow
    await deployment.upload_to_storage(ignore_file=ignore_file)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/prefect/deployments.py", line 576, in upload_to_storage
    file_count = await self.storage.put_directory(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/prefect/filesystems.py", line 479, in put_directory
    return await self.filesystem.put_directory(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/prefect/filesystems.py", line 356, in put_directory
    self.filesystem.put_file(f, fpath, overwrite=True)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/fsspec/asyn.py", line 113, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/fsspec/asyn.py", line 98, in sync
    raise return_result
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/s3fs/core.py", line 1073, in _put_file
    await self._call_s3(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/s3fs/core.py", line [33](https://github.com/jralduaveuthey/dataflow-ops/actions/runs/3541983497/jobs/5946948982#step:9:34)9, in _call_s3
    return await _error_wrapper(
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/s3fs/core.py", line 1[39](https://github.com/jralduaveuthey/dataflow-ops/actions/runs/3541983497/jobs/5946948982#step:9:40), in _error_wrapper
    raise err
PermissionError: Access Denied
Error: Process completed with exit code 1.
```

**Comment by anna-geller** [comment]
Thanks for the issue - it looks like your S3 block doesn't have credentials attached to it. Can you try setting those explicitly as shown here?

```python
from prefect.filesystems import S3
s3 = S3(
    bucket_path="prefect-orion/prod",
    aws_access_key_id="xxxx",
    aws_secret_access_key="xxxx",
)
print(f'S3 block: {s3.save("prod", overwrite=True)}')
```

**Comment by jralduaveuthey** [comment]
Thanks for the fast reply!
Unfortunately I did that and still same error. I also tried to set the AWS keys manually on the block on the Prefect Cloud and did not fix it either :/ 

The error seems to be when adding an object to a bucket (calling the PutObject operation), but in my S3 there is no new bucket created. Should a S3 bucket be created in a previous step before there is an attempt to add an object to it? 

Also in [your video](https://www.youtube.com/watch?v=Eemq2X9XrlE&t=120s) your S3 block credentials look[ like this](https://photos.google.com/share/AF1QipN_Cjs7XCKpfJsZYLMgCfOPKwYxG7A5tY6AB-NkI-N8C_1BSCWFcLqMQ0RYJgZ7-A?key=ckQwaGRnQUhlSkNyX2ZrVXJNTVl3TVF3M1pMaFVB) and [mine](https://photos.google.com/share/AF1QipPHUwPkXf8KttG3-Nu9qKJSIuTXKnrCd6Cst0QH34DZJgvmjxJni3ydD_S-6ANCJg/photo/AF1QipPFbctGCWFMJXYL9JMqSqF6aE1e6D3M4HmFYHaY?key=dm1pRC0zVEl1YVc5N1ljaXJIQU9rX1c5UXQxa2ZB) does not show the last characters, does it mean anything?

Thanks!

**Comment by anna-geller** [comment]
it's only because we changed it so we obfuscate the whole string

yes, you need to create your own bucket. You can't use mine, unfortunately :) prefect-orion is my private bucket

**Comment by jralduaveuthey** [comment]
my bad I thought it created the S3 also automatically in the stack. I guess I was trying yours if you are in eu-central-1 x)
Thanks!

**Comment by anna-geller** [comment]
yup, you're spot on, you need your own bucket
